INSERT INTO users VALUES 
(default, 'l', 'f78908fa8567611f02e5e359af4610e8665234a725ec18b2fb4e65068041e413f9bc150cb24c63ce0c1a7f6bf5d99e7bc2a81a32e94a51ce68a27be2350b6d06', '129137e12618d3264c136f6d2533cc12');
-- pw is 'l'

INSERT INTO categories_bool VALUES 
(default, 'Leo Bass', 't', (SELECT id FROM users WHERE username = 'l'));

INSERT INTO categories_num VALUES 
(default, 'BPM', 't', 0, 201, (SELECT id FROM users WHERE username = 'l'));

INSERT INTO categories_string_single VALUES 
(default, 'Leadsinger', 't', (SELECT id FROM users WHERE username = 'l'));

INSERT INTO categories_string_single_values VALUES 
('Mary', (SELECT id FROM categories_string_single WHERE name = 'Leadsinger')),
('Lucas', (SELECT id FROM categories_string_single WHERE name = 'Leadsinger')),
('Julian', (SELECT id FROM categories_string_single WHERE name = 'Leadsinger')),
('Jakob', (SELECT id FROM categories_string_single WHERE name = 'Leadsinger')),
('Duett (Mary/Lucas)', (SELECT id FROM categories_string_single WHERE name = 'Leadsinger')),
('Duett (sonst.)', (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'));


INSERT INTO categories_string_multiple VALUES
(default, 'Backingvocals', 't', (SELECT id FROM users WHERE username = 'l'));

INSERT INTO categories_string_multiple_values VALUES
('Mary', (SELECT id FROM categories_string_multiple WHERE name = 'Backingvocals')),
('Lucas', (SELECT id FROM categories_string_multiple WHERE name = 'Backingvocals')),
('Julian', (SELECT id FROM categories_string_multiple WHERE name = 'Backingvocals')),
('Jakob', (SELECT id FROM categories_string_multiple WHERE name = 'Backingvocals')),
('Daniel', (SELECT id FROM categories_string_multiple WHERE name = 'Backingvocals'));
INSERT INTO songs VALUES
(default, '1000 und 1 Nacht', 'Klaus Lage', 215, '', (SELECT id FROM users WHERE username = 'l')),
(default, '500 Miles', 'The Proclaimers', 229, '', (SELECT id FROM users WHERE username = 'l')),
(default, '99 Luftballons', 'Nena', 234, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Aber bitte mit Sahne', 'Udo Jürgens', 210, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'All Star', 'Smash Mouth', 202, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Alles Neu', 'Peter Fox', 285, 'Perc. Lucas/Flo', (SELECT id FROM users WHERE username = 'l')),
(default, 'Angels', 'Robbie Williams', 279, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Bad Romance', 'Lady Gaga', 318, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Basket Case', 'Green Day', 181, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Bohemian Rhapsody', 'Queen', 355, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Boulevard of broken dreams', 'Green Day', 261, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Brenna tuats guad', 'Hubert von Goisern', 224, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Britney Spears Medley', 'Britney Spears', 295, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Can''t fight this feeling', 'REO Speedwagon', 294, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Can''t stop', 'Red Hot Chili Peppers', 269, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Creep', 'Radiohead', 238, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Dance with somebody', 'Mando Diao', 246, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Dancing Queen', 'ABBA', 188, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Disney Medley', 'Seven Heaven', 487, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Don''t stop believing', 'The Journey', 241, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Don''t stop me now', 'Queen', 262, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Du entschuldige i kenn di', 'Peter Cornelius', 272, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Ein Kompliment', 'Sportfreunde Stiller', 198, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Expresso & Tschianti', 'Josh.', 179, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Fireflies', 'Owl City', 226, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Footloose', 'Kenny Loggins', 272, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Fürstenfeld', 'S.T.S', 342, 'Mary Hauptstimme (Intro, Refrain)', (SELECT id FROM users WHERE username = 'l')),
(default, 'Gimme Gimme Gimme', 'ABBA', 307, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Grace Kelly', 'MIKA', 183, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Great Balls of Fire', 'Jerry Lee Lewis', 164, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Griechischer Wein', 'Udo Jürgens', 254, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Ham kummst', 'Seiler und Speer', 272, 'Daniel Cajon', (SELECT id FROM users WHERE username = 'l')),
(default, 'Hey Jude', 'The Beatles', 320, '"Na na na na" Mary, Lucas Backings', (SELECT id FROM users WHERE username = 'l')),
(default, 'Hold the line', 'Toto', 236, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Holiday', 'Green Day', 213, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Hollywood Hills', 'Sunrise Avenue', 210, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Hooked on a feeling', 'Blue Swede, Bkörn Skifs', 172, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Hot stuff', 'Donna Summer', 314, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Hotel California', 'The Eagles', 381, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Hurra die Schule brennt', 'Extrabreit', 154, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'I will survive', 'Gloria Gaynor', 321, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Irgendwie Irgendwo Irgendwann', 'Nena', 234, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'It''s my life', 'Bon Jovi', 224, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Jailhouse Rock', 'The Blues Brothers', 217, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Jerk it out', 'Caesars', 201, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Jetlag', 'Simple Plan', 204, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Jump', 'Van Halen', 239, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Just the two of us', 'Grover Washington', 269, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Levitating', 'Dua Lipa', 207, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Little talks', 'Of Monsters and Men', 266, 'Flo Trompete', (SELECT id FROM users WHERE username = 'l')),
(default, 'Livin'' on a prayer', 'Bon Jovi', 250, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Major Tom', 'Peter Schilling', 286, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Mamma Mia', 'ABBA', 215, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Mit 66 Jahren', 'Udo Jürgens', 232, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Money for nothing', 'Dire Straits', 316, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'More than you know', 'Axwell /\ Ingrosso', 209, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Mr. Brightside', 'The Killers', 262, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Narcotic', 'Liquido', 252, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Ohne dich', 'Münchner Freiheit', 234, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Papaoutai', 'Stromae', 232, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Perfekte Welle', 'Juli', 205, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Piano Man', 'Billy Joel', 324, 'Flo Mundharmonika', (SELECT id FROM users WHERE username = 'l')),
(default, 'Que sera sera', 'Doris Day', 176, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Rock around the clock', 'Bill Haley & His Comets', 195, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Rockin'' all over the world', 'Status Quo', 216, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Rolling in the deep', 'Adele', 228, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Ruby', 'Kaiser Chiefs', 195, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'S&M', 'Rihanna', 240, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Sarà perché ti amo', 'Ricchi & Poveri', 190, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Schickeria', 'Spider Murphy Gang', 286, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Schrei nach Liebe', 'Die Ärzte', 196, 'Luisa Hauptstimme Prechorus', (SELECT id FROM users WHERE username = 'l')),
(default, 'Se bastasse una canzone', 'Eros Ramazotti', 333, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Seven nation army', 'The White Stripes', 600, 'Genre Medley', (SELECT id FROM users WHERE username = 'l')),
(default, 'Seven Nation Army Walzer', 'Seven Heaven', 334, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Sex on fire', 'Kings of Leon', 205, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Shallow', 'Lady Gaga', 221, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Shut up and dance', 'WALK THE MOON', 218, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Skandal im Sperrbezirk', 'Spider Murphy Gang', 229, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Skyfall', 'Adele', 289, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'So What', 'P!nk', 222, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Sommer in der Stadt', 'Spider Murphy Gang', 189, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Sternenhimmel', 'Hubert Kah', 209, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Summer of ''69', 'Bryan Adams', 216, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Sweet Caroline', 'DJ Ötzi', 226, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Sweet home Chicago', 'The Blues Brothers', 420, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Tage wie diese', 'Die Toten Hosen', 282, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'The Best', 'Tina Turner', 252, 'Jakob Saxophon Solo (Lucas Mic)', (SELECT id FROM users WHERE username = 'l')),
(default, 'The greatest show', 'The Greatest Showman', 302, 'Flo Trompete am Anfang', (SELECT id FROM users WHERE username = 'l')),
(default, 'This is the life', 'Amy Macdonald', 186, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'This love', 'Maroon 5', 207, 'Lucas Refrain Backings', (SELECT id FROM users WHERE username = 'l')),
(default, 'Time Warp', 'Rocky Horror Picture Show', 293, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Viva la vida', 'Coldplay', 242, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Vo Mello bis ge Schoppornou', 'Holstuonarmusicbigbandclub', 263, 'Jakob Beatbox', (SELECT id FROM users WHERE username = 'l')),
(default, 'Waterloo', 'ABBA', 168, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Weiß der Geier', 'Wolfgang Petry', 221, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Westerland', 'Die Ärzte', 232, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Weusd'' a Herz hast', 'Rainhard Fendrich', 199, 'Jakob Saxophon', (SELECT id FROM users WHERE username = 'l')),
(default, 'What''s up', '4 Non Blondes', 313, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Whatever it takes', 'Imagine Dragons', 201, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Willst du', 'Alligatoah', 224, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Wonderwall', 'Oasis', 258, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Zombie', 'The Cranberries', 315, '', (SELECT id FROM users WHERE username = 'l')),
(default, 'Zruck zu dir', 'Nickerbocker, Biene', 222, '', (SELECT id FROM users WHERE username = 'l'));

INSERT INTO properties_bool VALUES
((SELECT id FROM songs WHERE title = 'Aber bitte mit Sahne'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Alles Neu'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Brenna tuats guad'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Can''t fight this feeling'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Du entschuldige i kenn di'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Fürstenfeld'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Griechischer Wein'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Ham kummst'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Hooked on a feeling'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Mit 66 Jahren'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Papaoutai'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Schickeria'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Sommer in der Stadt'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Vo Mello bis ge Schoppornou'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Weusd'' a Herz hast'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Whatever it takes'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't'),
((SELECT id FROM songs WHERE title = 'Wonderwall'), (SELECT id FROM categories_bool WHERE name='Leo Bass'), 't');

INSERT INTO properties_string_single VALUES
((SELECT id FROM songs WHERE title = '1000 und 1 Nacht'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = '500 Miles'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = '99 Luftballons'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Aber bitte mit Sahne'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'All Star'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Alles Neu'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Angels'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Bad Romance'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Basket Case'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Bohemian Rhapsody'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Boulevard of broken dreams'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Brenna tuats guad'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Britney Spears Medley'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Can''t fight this feeling'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Can''t stop'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Creep'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Dance with somebody'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Dancing Queen'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Disney Medley'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Don''t stop believing'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Don''t stop me now'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Du entschuldige i kenn di'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Ein Kompliment'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Expresso & Tschianti'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Fireflies'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Footloose'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Fürstenfeld'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Gimme Gimme Gimme'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Grace Kelly'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Great Balls of Fire'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Griechischer Wein'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Ham kummst'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Hey Jude'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Hold the line'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Holiday'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Hollywood Hills'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Hooked on a feeling'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Hot stuff'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Hotel California'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Hurra die Schule brennt'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'I will survive'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Irgendwie Irgendwo Irgendwann'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'It''s my life'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Jailhouse Rock'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Jerk it out'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Jetlag'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Jump'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Just the two of us'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Levitating'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Little talks'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Livin'' on a prayer'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Major Tom'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Mamma Mia'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Mit 66 Jahren'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Money for nothing'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'More than you know'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Mr. Brightside'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Narcotic'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Ohne dich'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Papaoutai'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Perfekte Welle'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Piano Man'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Jakob'),
((SELECT id FROM songs WHERE title = 'Que sera sera'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Rock around the clock'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Rockin'' all over the world'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Rolling in the deep'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Ruby'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'S&M'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Sarà perché ti amo'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Schickeria'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Schrei nach Liebe'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Se bastasse una canzone'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Seven nation army'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Seven Nation Army Walzer'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Sex on fire'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Shallow'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (sonst.)'),
((SELECT id FROM songs WHERE title = 'Shut up and dance'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Skandal im Sperrbezirk'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Skyfall'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'So What'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Sommer in der Stadt'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Sternenhimmel'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Summer of ''69'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Sweet Caroline'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Sweet home Chicago'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Tage wie diese'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'The Best'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'The greatest show'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'This is the life'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'This love'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Time Warp'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)'),
((SELECT id FROM songs WHERE title = 'Viva la vida'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Vo Mello bis ge Schoppornou'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Waterloo'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Weiß der Geier'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Westerland'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Lucas'),
((SELECT id FROM songs WHERE title = 'Weusd'' a Herz hast'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'What''s up'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Whatever it takes'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Willst du'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Jakob'),
((SELECT id FROM songs WHERE title = 'Wonderwall'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Julian'),
((SELECT id FROM songs WHERE title = 'Zombie'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Mary'),
((SELECT id FROM songs WHERE title = 'Zruck zu dir'), (SELECT id FROM categories_string_single WHERE name = 'Leadsinger'), 'Duett (Mary/Lucas)');

/*
SELECT s.id AS id, s.title AS title, coalesce(p.value, 'f') AS leobass
FROM songs s
LEFT OUTER JOIN (
    SELECT * FROM properties_bool
    WHERE category_id = (
        SELECT id FROM categories_bool
        WHERE name = 'Leo Bass'
    )
) p
ON s.id = p.song_id
LIMIT 10;
*/

-- INSERT INTO songs VALUES (default, 'holiday', 'green day', 180, '', (SELECT id FROM users WHERE username = 'l'));